### ISSUE TITLE
EMODnet data product author checklist

### ISSUE THREAD

**Issue by maelle** [EMODnet/seadog#17]
## General

- [ ] I have used EMODnet data product template.
- [ ] I have put together a clear README including
    - [ ] a title;
    - [ ] a description of about 300 words (including context, story);
    - [ ] keywords;
    - [ ] temporal coverage;
    - [ ] geographic coverage (MRGIDs from MarineRegions);
    - [ ] if applicable: Taxonomic coverage (AphiaIDs from WoRMS)
    - [ ] what datasets does this product uses? List the IMIS dasids, and/or DOIs from datasets not listed in IMIS.
   - [ ] Is this product a continuation of an older product? Does it uses another product? If yes, please provide its IMIS dasid.
- [ ] I have run a spell check on text parts.

## Authorship and citation

- [ ] I have listed all authors.
- [ ] I have listed contact information.
- [ ] I have added citation information in the README as: Last name, First name. Year. Title. Funding e.g.

```
Beauchard, Olivier, Herman, Peter M.J., Fernández-Bejarano, Salvador.  2021. Data product numerical abundance of benthic macroinvertebrates in  North Sea and Baltic Sea. Integrated data products created under the  European Marine Observation Data Network (EMODnet) Biology project  (EASME/EMFF/2017/1.3.1.2/02/SI2.789013), funded by the by the European  Union under Regulation (EU) No 508/2014 of the European Parliament and  of the Council of 15 May 2014 on the European Maritime and Fisheries  Fund.
```

(I might have added a [citation.cff](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) file)

## Code

- [ ] I have listed dependencies (e.g. with the renv R package).
- [ ] I have written how to re-run the code, e.g. in a main script that has commands.

## Data

- [ ] I have documented datasets e.g. with dataspice.

## Upkeep

- [ ] I have added a lifecycle badge to the README or some sentences about the project status.
- [ ] I have created a changelog (NEWS.md) for keeping tracks of changes.
- [ ] I have recruited a reviewer for the data product.
