### ISSUE TITLE
EMODnet data product reviewer checklist

### ISSUE THREAD

**Issue by maelle** [EMODnet/seadog#18]
## General

- [ ] The README gave a good overview and includes
    - [ ] a title;
    - [ ] a description of about 300 words (including context, story);
    - [ ] keywords;
    - [ ] temporal coverage;
    - [ ] geographic coverage (MRGIDs from MarineRegions);
    - [ ] if applicable: Taxonomic coverage (AphiaIDs from WoRMS)
    - [ ] what datasets does this product uses? List the IMIS dasids, and/or DOIs from datasets not listed in IMIS.
- [ ] The product includes [EMODnet recommended metadata](https://github.com/EMODnet/seadog/blob/main/inst/metadata-template.md).

## Authorship and citation

- [ ] There is citation information.
    - [ ] The citation format in the README is: Last name, First name. Year. Title.
- [ ] There is authors, and contact information.

## Code

- [ ] There are guidelines for re-running the code.
- [ ] I was able to run the code.
- [ ] The output did not change, or changed according to expectation (e.g. more occurrences).

## Data

- [ ] Datasets are documented with e.g. datascpice.
- [ ] I was able to read in and use datasets.

## Upkeep

- [ ] The README included a lifecycle badge or description.
- [ ] There is a changelog.
