### ISSUE TITLE
EMODnet data product reviewer checklist

### ISSUE THREAD

**Issue by maelle** [EMODnet/seadog#8]
## General

- [ ] The README gave a good overview.

## Authorship and citation

- [ ] There is citation information.
- [ ] There is authors, and contact information.

## Code

- [ ] There are guidelines for re-running the code.
- [ ] I was able to run the code.
- [ ] The output did not change, or changed according to expectation (e.g. more occurrences).

## Data

- [ ] Datasets are documented with e.g. datascpice.
- [ ] I was able to read in and use datasets.

## Upkeep

- [ ] The README included a lifecycle badge or description.
- [ ] There is a changelog.
