### ISSUE TITLE
EMODnet data product author checklist

### ISSUE THREAD

**Issue by maelle** [EMODnet/seadog#9]
## General

- [ ] I have used EMODnet data product template.
- [ ] I have put together a clear README.
- [ ] I have run a spell check on text parts.

## Authorship and citation

- [ ] I have listed all authors.
- [ ] I have listed contact information.
- [ ] I have added citation information in the README and/or a [citation.cff](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) file.

## Code

- [ ] I have listed dependencies (e.g. with the renv R package).
- [ ] I have written how to re-run the code, e.g. in a main script that has commands.

## Data

- [ ] I have documented datasets e.g. with dataspice.

## Upkeep

- [ ] I have added a lifecycle badge to the README or some sentences about the project status.
- [ ] I have created a changelog (NEWS.md) for keeping tracks of changes.
